#!/usr/bin/env node
// email-agent — Deliver reports via HTML email
const fs = require('fs');

function generateEmailHtml(report) {
  const { site, summary, technical_seo, recommendations } = report;
  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"><style>
body{font-family:-apple-system,sans-serif;max-width:600px;margin:0 auto;padding:20px;color:#333}
.header{background:#2563eb;color:#fff;padding:24px;border-radius:8px;margin-bottom:24px}
.score{font-size:48px;font-weight:bold}
.grade{display:inline-block;padding:4px 12px;border-radius:4px;font-weight:bold;margin-left:8px}
.grade-A{background:#10b981;color:#fff}.grade-B{background:#f59e0b;color:#fff}
.grade-C{background:#f97316;color:#fff}.grade-D,.grade-F{background:#ef4444;color:#fff}
.card{background:#f9fafb;border-radius:8px;padding:16px;margin:12px 0}
.finding{padding:6px 0;border-bottom:1px solid #e5e7eb}
.error{color:#ef4444}.warning{color:#f59e0b}.info{color:#3b82f6}
.footer{margin-top:32px;padding-top:16px;border-top:1px solid #e5e7eb;font-size:12px;color:#9ca3af}
</style></head><body>
<div class="header"><h1>${site} — Weekly SEO Report</h1><p>${report.period}</p>
<div><span class="score">${summary.seo_score}</span><span class="grade grade-${summary.grade}">${summary.grade}</span></div></div>
<div class="card"><h3>Performance</h3>
<p>Load time: ${technical_seo.metrics_summary?.load_time ? technical_seo.metrics_summary.load_time+'ms' : 'N/A'} | Words: ${technical_seo.metrics_summary?.word_count || 'N/A'} | Title: ${technical_seo.metrics_summary?.title || 'N/A'}</p></div>
<div class="card"><h3>Issues</h3>${(technical_seo.top_findings||[]).map(f=>`<div class="finding ${f.severity}">${f.severity.toUpperCase()}: ${f.detail}</div>`).join('')||'<p>No issues!</p>'}</div>
${recommendations.length>0?`<div class="card"><h3>Recommendations</h3><ul>${recommendations.map(r=>`<li>${r}</li>`).join('')}</ul></div>`:''}
<div class="footer"><p>Generated by SearchOps AI | ${report.generated}<br>Full report: https://dashboard.searchops.ai/reports/${site}</p></div>
</body></html>`;
}

const [,, reportFile, emailTo] = process.argv;
if (!reportFile) { console.log('Usage: node email-agent.js <report.json> [email@example.com]'); process.exit(1); }
const report = JSON.parse(fs.readFileSync(reportFile, 'utf8'));
const html = generateEmailHtml(report);
if (emailTo) {
  console.log(`[EMAIL] To: ${emailTo}, Subject: ${report.site} — Weekly SEO Report (${report.summary.grade})`);
  const outFile = reportFile.replace('.json', '.email.html');
  fs.writeFileSync(outFile, html);
  console.log(`HTML saved: ${outFile}`);
} else { console.log(html); }
